### PR TITLE
Modlist rework (now with zbighuge performance improvements!)

### PR DESCRIPTION
**Pull request by JuiceyBeans**
**Breaking changes:**
- Water condensers will disappear and need to be replaced by water collectors

**Other:**
- Leaky report threshold bumped from 80 to 200 

**Added:**
- Lootr (361276): #114
- Monazite (1015315): #151
- Water Collector (1016115)

**Removed:**
- Artan'sProjectCoreMod (585454): Unused library
- Lemon Lib (471136): Unused library (originally used by MiniUtils)
- Patchouli (306770): Unused library
- TexTrue's Embeddium Options (910506): Included in Embeddium
- Water condenser (663013): Replaced by Water Collector
- Stack Refill (411813): Obsolete, added by Inventory Tweaks Refoxed
- KleeSlabs (241895): Breaks GT hammers
- 3D Skin Layers (521480): Clientside, can be added by players if they really want it; adds nothing to the modpack
- Overloaded Armor Bar (314002): Moni is peaceful and doesn't have many armor sets that go over the vanilla limit
- Saturn (670986) Increases memory usage for some reason; CPU improvements are negligible and the tradeoff is not worth it imo; more in #102
- No Auto Jump (282099): Same as above; removes an accessibility option
- Ender Crop (242269): Obsolete, HNN is faster and usually obtained before an actual ender crop (Technically required for Enderman model)
- AE2 QoL Recipes (907026): All this mod adds is a bunch of recipes, the mod itself is empty otherwise. Implemented via KJS instead
- Energy Meter (532169): Quote from Xefyr0: ``This thing allows for the transfer of up to 1 GFE/t, as opposed to the Draconic Superconductor Conduit's 134MFE/t. If you want conduit progression to have some weight then this is worth removing``

**Feedback required before removing:**
- Showcase Item (627196): Clientside, can be added by players if they really want it; adds nothing to the modpack
- FTB Quests Optimizer: Not required on client, could just pack it with server files instead
- Smooth Boot: Doesn't seem to do much
- Smooth chunk save: Testing required

**Updated:**
image

### CODE REVIEW

**Comment by LetterN** [comment]
- keep 551314
- keep 282099 i do not want to reset my `options.txt` every time i git pull/swap branch etc
- keep 242269 early ender pearl same as nomi

**Comment by JuiceyBeans** [comment]
To be noted: Ender pearls can be made by alloy smelting a diamond with pulsating dust (which can be obtained by smelting uraninite dust too) at LV. They also spawn in Lost Cities chests

**Comment by WithersChat** [comment]
> keep 551314 [No Recipe Book Reborn]
Agreed
> keep 282099 [No Auto Jump] i do not want to reset my `options.txt` every time i git pull/swap branch etc
I think we should just get rid of it and let people disable auto-jump. I never feel good about removing an option from Accessibility Settings, y'know?
> keep 242269 [Ender Crop] early ender pearl same as nomi
As Juicy said, 2 other ways to get it. Also Ender Crop literally requires 4 pearls to craft so it doesn't replace anything already done by something else.

**Comment by Xefyr0** [comment]
I would also like the removal of Waystones, or else its replacement with Tempad.

Either way, /home from FTBUtils already exists.

**Comment by Leclowndu93150** [comment]
Keep Forge CIT, i used it to reskin the jetpacks and components because they have NBT

**Comment by JuiceyBeans** [comment]
> I would also like the removal of Waystones, or else its replacement with Tempad.
> 
> Either way, /home from FTBUtils already exists.

Waystones was always meant to be temporary iirc, will talk about Tempad with Pansmith

**Comment by JuiceyBeans** [comment]
### Current state:

Added:
- Lootr

Removed:
- Artan'sProjectCoreMod
- KleeSlabs
- Leaky
- LemonLib
- Overloaded Armor Bar
- Saturn
- Skin Layers 3D
- Stack Refill

**Comment by JuiceyBeans** [comment]
Updated feedback required section, would love some rn

**Comment by ThePansmith** [comment]
Was actually in the middle of typing that lol:

Added:
    Lootr
    Monazite
Keep: 
    WaterFrames (Shitposty images are good for morale :trollface:, could possibly be removed once the Central Monitor gets ported)
    Wireless Chargers (We lack a way to wirelessly charge things)
    WaterCondenser (Sure, the water pump exists, but this is supposed to be a earlygame compact option. I do want to write my own version of this mod where it will autopush water)
Remove:
    Artan'sProjectCoreMod
    KleeSlabs
    Leaky (Could possibly leave the config for this one in, bumped up to like 200 items or something, just to help servers)
    LemonLib
    Overloaded Armor Bar
    Saturn
    Skin Layers 3D
    Stack Refill
    Ender Crop
    No Auto Jump
    AE2 QoL Recipes (Implement as a KJS script before removal)
    Energy Meter

**Comment by Leclowndu93150** [comment]
I can propose to write the Water Collector mod

**Comment by JuiceyBeans** [comment]
Performance seems to have increased not insignificantly after updating mods

**Comment by SrRapero720** [comment]
I reduced the watermedia jar to 26mb (clearly a feature)

**Pull request merged**
