### PR TITLE
Update the description of golden furnace

### LINKED ISSUE #526: [Bug]: Wrong Description for Golden Furnace
### Issue Summary

The description in MEI says "Cooktime: 60" but the quest book says it should only take 40

Screenshot 2024-08-13 154957

### Reproduction steps

1. open the modpack
2. hover your mouse over the item "golden furnace"
3. Read the description

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Yokoharu**
Fixes #526

### CODE REVIEW

**Comment by SwarabRaul** [comment]
I think the quest book was right, the golden furnace is supposed to be the 40 ticks it's a replacement of emerald furnace which is something we can't craft, and in Nomifactory's quest book as well the processing speed is 40 ticks.

**Comment by Yokoharu** [comment]
Does it? It takes 3 seconds to cook an item which is 60 ticks i think.

**Comment by SwarabRaul** [comment]
You can modify the cook time to 40 ticks, using it's config file. Oh well, I am not sure what it should be, but either way it's alright.

**Comment by ThePansmith** [comment]
Closed by #585

**Pull request closed without merging**
