### PR TITLE
Edited The Beginning and Processing Lines chapters to be more in line with Harder Mode

### PR DESCRIPTION
**Pull request by Eterxity**
Edits in _The Beginning_:
In Harder Mode, alloy smelting Steel is disabled in favor of the Primitive Blast Furnace. The questbook still has the quest written as "Alloying Steel" with the intent of telling the players to use the alloy smelter to make steel, which is impossible in Harder Mode. The quest of making Steam Turbines from thermal is impossible as there is no recipe for the Steam Pipe in Harder Mode. 

Edits in _Processing Lines_:
I removed the processing line to make a prediction matrix as HNN is disabled in Harder Mode.

I was going to delete the HNN  chapter but I couldn't figure out how to do it.

I have attached screenshots of the quests after being edited:

image_2024-09-24_184552278
image_2024-09-24_184616476

### CODE REVIEW

**Comment by Eterxity** [comment]
I just realized that completely removing the Thermal Steam Turbine quest was also an option because that will pretty much not be used at all in Harder Mode.

**Review by Xefyr0 — CHANGES_REQUESTED** [review]
No need to create an override for the processing lines chapter - the HNN loop should be invisible when not in editing mode.

If you could, please resolve the merge conflicts while you're at it.

**Comment by Eterxity** [comment]
crap wrong button

**Comment by Eterxity** [comment]
actually did changed, clicked wrong button earlier sorry

**Comment by Eterxity** [comment]
not sure if it's normal, but the changes said I removed a bunch of stuff I didn't but its fine for me in game

**Review by Eterxity — COMMENTED** [review]
not sure why things got removed. quests are fine in game however. going to try to see what happened cause I didn't remove any lines. (or I'm just stupid)

**Pull request merged**
