### PR TITLE
Add Ensorcellation + Config

### LINKED ISSUE #1013: [Feature]: Add Ensorcellation for utility enchantments to assist with building
### Suggestion

[Ensorcellation](https://www.curseforge.com/minecraft/mc-mods/ensorcellation) is a mod by Team CoFH that adds various enchantments. Most are related to combat and should probably be disabled in config for this pack, but there are two enchantments that I bet almost every builder would appreciate.

- Reach on chestplate increases block placement/destruction range, which means you don't have to get nearly as close to the ground when flying to work on your factory. Additionally it would further incentivize use of a magnet, so you can actually pick up blocks that you break with your increased reach.

- Air Affinity on helmet removes the penalty to block breaking while not on ground. Red Hook already does this, so having a way to break blocks at a reasonable speed while flying would increase QoL for Angel Ring users (Jetpack users too unless that mod already has a solution for this).

Whether the mod is added to the pack or made into optional compat, these enchantments should get EnderIO enchanter recipes as well.

### PR DESCRIPTION
**Pull request by Echoloquate**
Disabled most enchants because they are combat related, just Air Affinity (removes flying penalty from breaking blocks) and Reach (Exactly what it says)

Closes #1013

### CODE REVIEW

**Comment by ThePansmith** [comment]
Add recipes for these books in EIO's enchanter

**Comment by Echoloquate** [comment]
Added them, I figured the effortless building reach upgrade was cheap enough to be ok for reach but happy to change it to something else

**Comment by Echoloquate** [comment]
Actually I've got better items, don't merge yet

**Comment by Echoloquate** [comment]
image
image

**Pull request merged**
