### PR TITLE
The Absolutely Monstrous Multiblock PR

### PR DESCRIPTION
**Pull request by JuiceyBeans**
## To-do:
- [x] Remove Superfab, Supersim, SDA in hard mode
- [x] Add Universal Crystallizer, Actualization Chamber to hard mode
- [x] Add recipes for above
- [x] New micro miners (tier 4.5, 8.5, stabilized 1 to 8.5)
- [x] Missions for tier 4.5 and 8.5
- [x] Fix ALL broken microminer stuff. Even normal mode. (feature creep who?)

## Other stuff:
- Instructions to README.md on how to enable hard/harder modes
- Fix a couple of microverse recipes
- LOTS of tooltip fixes
- Remove tier restrictions from all ExCrafting recipes
- Tag for microminers
- Localisation for SDA, empowered emeradic crystal, holmium oxide
- Dense magma block
- Unused stabilized T9 and T10 for future use (Withers mentioned higher tier pristines eventually)
- Change Reactor Stabilizer and Reactor Core from items to blocks (for use in multis)

Should finish #208 and #207

### CODE REVIEW

**Comment by WithersChat** [comment]
Omega will probably be a different download BTW, because the changes would be too deep.

**Comment by ThePansmith** [comment]
Should mark your PR as a draft until you are done

**Comment by JuiceyBeans** [comment]
Dawg I fuckin hate resolving conflicts

**Comment by JuiceyBeans** [comment]
At long last....

**Pull request merged**
